name: Download and Package Python Wheels

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    paths:
      - 'requirements.txt'  # 当requirements.txt变更时自动触发

jobs:
  download-wheels:
    name: Download ARM64 Python Wheels
    runs-on: ubuntu-22.04
    # 使用arm64架构
    container:
      image: ubuntu:22.04
      options: --platform linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install pip and wheel
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Create wheels directory
        run: mkdir -p wheels

      - name: Download ARM64 wheels
        run: |
          # 读取requirements.txt并下载所有依赖的arm64 wheel包
          pip download --only-binary=:all: --platform manylinux2014_aarch64 \
            --implementation cp --python-version 3.12 --abi cp312 \
            -r requirements.txt -d wheels/

      - name: Package wheels
        run: |
          # 将所有wheel包打包成zip文件
          zip -r python-wheels-arm64.zip wheels/

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-arm64
          path: python-wheels-arm64.zip
          retention-days: 30  # 保留30天供下载
