name: Download ARM64 Wheels on OpenEuler

# 触发条件: 可以根据需要修改，这里设置为手动触发
on:
  workflow_dispatch:

jobs:
  build-and-download-wheels:
    # 使用ARM64架构的OpenEuler-22.03环境
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:22.03-lts-sp3
      options: --platform linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 检出代码，获取项目中的requirements.txt

      - name: Install necessary system packages
        run: |
          # 更新系统并安装必要依赖
          dnf update -y
          dnf install -y wget tar gcc make openssl-devel bzip2-devel libffi-devel

      - name: Install Python 3.12 from source
        run: |
          # 从源码编译安装指定版本的Python 3.12
          wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
          tar -xzf Python-3.12.0.tgz
          cd Python-3.12.0
          ./configure --enable-optimizations
          make -j$(nproc)
          make altinstall  # 使用altinstall避免覆盖系统默认Python
          ln -s /usr/local/bin/python3.12 /usr/local/bin/python
          ln -s /usr/local/bin/pip3.12 /usr/local/bin/pip

      - name: Verify Python and pip versions
        run: |
          # 验证Python和pip版本是否符合要求
          python --version
          pip --version
          # 确保pip版本为24.0，如果不是则升级
          pip install --upgrade pip==24.0

      - name: Create directory for wheels
        run: |
          # 创建目录用于存储下载的wheel包
          mkdir -p arm64_wheels

      - name: Download ARM64 wheels
        run: |
          # 下载requirements.txt中所有依赖的ARM64版本wheel包
          # --only-binary=:all: 确保只下载二进制wheel包
          # --platform manylinux2014_aarch64 指定ARM64平台
          # -d 指定下载目录
          pip download --only-binary=:all: --platform manylinux2014_aarch64 -r requirements.txt -d arm64_wheels/

      - name: Package wheels
        run: |
          # 将所有wheel包打包成tar.gz文件，方便上传
          tar -czf arm64_wheels_$(date +%Y%m%d_%H%M%S).tar.gz arm64_wheels/

      - name: Upload wheel package
        uses: actions/upload-artifact@v4
        with:
          name: openeuler-arm64-python-wheels
          path: ./*.tar.gz
          # 保留Artifact 30天，可根据需要调整
          retention-days: 30
