name: Download ARM64 Wheels on Ubuntu 22.04

# 触发方式：手动触发
on:
  workflow_dispatch:

jobs:
  download-arm64-wheels:
    # 使用Ubuntu 22.04作为基础系统
    runs-on: ubuntu-22.04
    # 启用ARM64架构支持
    env:
      TARGET_ARCH: aarch64
      PYTHON_VERSION: 3.12.0
      PIP_VERSION: 24.0

    steps:
      - name: Set up QEMU for ARM64 emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
        # 安装QEMU模拟器以支持ARM64架构

      - name: Checkout repository
        uses: actions/checkout@v4
        # 检出代码仓库，获取requirements.txt文件

      - name: Run commands in Ubuntu 22.04 ARM64 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:22.04
          platform: linux/arm64
          # 使用ARM64架构的Ubuntu 22.04容器
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          # 将工作目录挂载到容器中，确保文件共享

          run: |
            # 更新系统并安装必要工具
            apt-get update && apt-get install -y \
              wget \
              build-essential \
              libssl-dev \
              zlib1g-dev \
              libbz2-dev \
              libreadline-dev \
              libsqlite3-dev \
              curl \
              libncursesw5-dev \
              xz-utils \
              tk-dev \
              libxml2-dev \
              libxmlsec1-dev \
              libffi-dev \
              liblzma-dev

            # 下载并安装指定版本的Python
            wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
            tar -xzf Python-${PYTHON_VERSION}.tgz
            cd Python-${PYTHON_VERSION}
            ./configure --enable-optimizations --prefix=/usr/local
            make -j$(nproc)
            make altinstall

            # 创建Python和pip的符号链接
            ln -s /usr/local/bin/python3.12 /usr/local/bin/python
            ln -s /usr/local/bin/pip3.12 /usr/local/bin/pip

            # 验证Python版本
            echo "Python version:"
            python --version
            
            # 升级到指定版本的pip
            pip install --upgrade pip==${PIP_VERSION}
            echo "Pip version:"
            pip --version

            # 创建存储wheel包的目录
            mkdir -p arm64_wheels

            # 从requirements.txt下载所有ARM64架构的wheel包
            pip download \
              --only-binary=:all: \
              --platform manylinux2014_aarch64 \
              -r requirements.txt \
              -d arm64_wheels/

            # 打包wheel文件
            tar -czf ubuntu2204_arm64_wheels_$(date +%Y%m%d_%H%M%S).tar.gz arm64_wheels/

      - name: Upload wheel package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu2204-arm64-python-wheels
          path: ./*.tar.gz
          retention-days: 30
          # 保存30天，可在Actions结果页面获取下载链接
    
