name: Download openEuler Packages (With All Repos)

on:
  workflow_dispatch:
    inputs:
      packages:
        description: '需要下载的软件包（空格分隔）'
        required: true
        default: 'screen tmux htop'
        type: string

jobs:
  build-repo:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: 启动openEuler容器
        run: |
          docker run --rm --name openeuler-pkg-downloader -d \
            --platform linux/arm64 \
            --init \
            openeuler/openeuler:22.03 \
            /bin/sh -c "while true; do sleep 3600; done"
          
          # 等待容器启动
          for i in {1..10}; do
            if docker inspect -f '{{.State.Running}}' openeuler-pkg-downloader &> /dev/null; then
              echo "容器已运行"
              break
            fi
            sleep 3
          done

      - name: 查询容器系统基本信息
        run: |
          echo "===== 查看内核信息 ====="
          docker exec openeuler-pkg-downloader uname -ar
          
          echo -e "\n===== 查看操作系统版本 ====="
          docker exec openeuler-pkg-downloader cat /etc/os-release
          
          echo -e "\n===== 查看原始yum仓库配置 ====="
          docker exec openeuler-pkg-downloader cat /etc/yum.repos.d/openEuler.repo
          
          echo -e "\n===== 查看磁盘空间 ====="
          docker exec openeuler-pkg-downloader df -h
          
          echo -e "\n===== 查看已启用的仓库 ====="
          docker exec openeuler-pkg-downloader dnf repolist enabled

          echo -e "\n===== 查看容器信息 ====="
          docker inspect openeuler-pkg-downloader

      - name: 替换仓库为国内镜像（保留所有仓库）
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            # 替换默认源为华为云镜像（保留所有仓库配置）
            sed -i 's|repo.openeuler.org|mirrors.huaweicloud.com/openeuler|g' /etc/yum.repos.d/openEuler.repo
            
            # 清理并重建缓存
            dnf clean all
            dnf makecache
          "

      - name: 查看替换后的仓库配置
        run: |
          echo "===== 替换后的yum仓库配置 ====="
          docker exec openeuler-pkg-downloader cat /etc/yum.repos.d/openEuler.repo

      - name: 安装必要工具
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            # 安装dnf-utils（替代yum-utils）和createrepo_c
            dnf install -y dnf-utils createrepo_c
          "

      - name: 下载软件包及依赖
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            mkdir -p /packages/rpms
            PACKAGES=(${INPUT_PACKAGES})
            # 使用dnf download下载指定包及所有依赖
            dnf download --resolve --destdir=/packages/rpms \"\${PACKAGES[@]}\"
          "
        env:
          INPUT_PACKAGES: ${{ github.event.inputs.packages }}

      - name: 查看下载的软件包列表
        run: |
          echo "===== 下载的RPM包列表 ====="
          docker exec openeuler-pkg-downloader ls -lh /packages/rpms

      - name: 生成本地仓库元数据
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            createrepo_c /packages/rpms
          "

      - name: 打包仓库文件
        run: |
          docker cp openeuler-pkg-downloader:/packages ./
          tar -czf openeuler-packages.tar.gz ./packages
          docker stop openeuler-pkg-downloader

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: openeuler-22.03-packages
          path: openeuler-packages.tar.gz
          retention-days: 3
