name: Download openEuler RPM Packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: '需要下载的软件包（空格分隔）'
        required: true
        default: 'screen tmux htop'
        type: string

jobs:
  build-repo:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: 启动openEuler容器并保持运行
        run: |
          # 使用--init确保容器正确处理信号，避免意外退出
          docker run --rm --name openeuler-pkg-downloader -d \
            --platform linux/arm64 \
            --init \
            openeuler/openeuler:22.03 \
            /bin/sh -c "while true; do sleep 3600; done"  # 持续运行容器
          docker ps -a
          docker inpect openeuler-pkg-downloader
          # 等待容器初始化完成（最多等待30秒）
          for i in {1..10}; do
            if docker inspect -f '{{.State.Running}}' openeuler-pkg-downloader &> /dev/null; then
              echo "容器已正常运行"
              break
            fi
            echo "等待容器启动..."
            sleep 3
          done

      - name: 检查容器状态
        run: |
          if ! docker inspect -f '{{.State.Running}}' openeuler-pkg-downloader | grep -q "true"; then
            echo "容器未正常运行，查看日志："
            docker logs openeuler-pkg-downloader
            exit 1
          fi

      - name: 初始化容器内环境
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            # 替换默认源为国内镜像（加速下载）
            sed -i 's|repo.openeuler.org|mirrors.huaweicloud.com/openeuler|g' /etc/yum.repos.d/openEuler.repo
            dnf clean all
            dnf makecache
            dnf update -y
            dnf install -y dnf-plugins-core yum-utils createrepo_c
          "

      - name: 创建下载目录
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            mkdir -p /packages/{rpms,repodata}
          "

      - name: 下载指定软件包及依赖
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            PACKAGES=(${INPUT_PACKAGES})
            yumdownloader --resolve --destdir=/packages/rpms \"\${PACKAGES[@]}\"
          "
        env:
          INPUT_PACKAGES: ${{ github.event.inputs.packages }}

      - name: 生成本地仓库元数据
        run: |
          docker exec openeuler-pkg-downloader bash -c "
            createrepo_c /packages/rpms
          "

      - name: 从容器复制文件到宿主
        run: |
          docker cp openeuler-pkg-downloader:/packages ./packages
          tar -czf openeuler-packages.tar.gz ./packages

      - name: 停止容器
        run: |
          docker stop openeuler-pkg-downloader

      - name: 上传打包文件
        uses: actions/upload-artifact@v4
        with:
          name: openeuler-22.03-packages
          path: openeuler-packages.tar.gz
          retention-days: 3
